###############################################
###
POST http://localhost:8080/api/palettes
Content-Type: application/json

{
  "name": "DataGen",
  "kafkaType": 1,
  "yamlPath": "connect.yaml",
  "commands": ["command/1"],
  "configTemplate": "[\"connect_name\", \"bootstrap_servers\", \"key_converter\", \"value_converter\", \"connect_replicas\"]"
}
###

POST http://localhost:8080/api/kubernetes/yaml
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="connect.yaml"
Content-Type: application/x-yaml

< /Users/eric.yoo/works/app-controller/K8s/connect.yaml
--WebAppBoundary--

###
POST http://localhost:8080/api/commands
Content-Type: application/json

{
  "name": "create",
  "commandType": 1,
  "palette": "palette/1",
  "httpMethod": "POST",
  "httpPath": "/connector",
  "httpBody": "{\"name\": \"my-datagen\",\"config\": {\"connector.class\": \"io.confluent.kafka.connect.datagen.DatagenConnector\", \"kafka.topic\": \"my-topic\", \"quickstart\": \"users\" }}"
}

###############################################
###
POST http://localhost:8080/api/workspaces
Content-Type: application/json

{
  "name": "data-get-test",
  "status": "Define",
  "config": "[{\"bootstrap_servers\":\"141.164.42.200:9092\"}, {\"key_converter\":\"org.apache.kafka.connect.json.JsonConverter\"}, {\"value_converter\":\"org.apache.kafka.connect.json.JsonConverter\"}, {\"connect_replicas\":1}]"
}

###
POST http://localhost:8080/api/topics
Content-Type: application/json

{
  "name": "data-gen-topic",
  "partitions": 1,
  "replicas": 1,
  "status": "Define",
  "config": ""
}

###
GET http://localhost:8080/api/workspaces
Content-Type: application/json
###
GET http://localhost:8080/api/palettes
Content-Type: application/json
###
GET http://localhost:8080/api/topics
Content-Type: application/json
###
GET http://localhost:8080/api/commands
Content-Type: application/json

###
POST http://localhost:8080/api/workloads
Content-Type: application/json

{
  "name": "data-gen-work",
  "palette": "palette/1",
  "status": "Define",
  "workspace": "workspace/1",
  "inputTopics": "[]",
  "outputTopics": "[\"data-gen-topic\"]",
  "config": "[{\"connect_name\":\"data-gen-work\"}]"
}

###############################################
###
POST http://localhost:8080/api/deploy/do/1
Content-Type: application/json

{}

###
GET http://localhost:8080/api/deploy/status/1
Content-Type: application/json

###
POST http://localhost:8080/api/deploy/status/1
Content-Type: application/json

{
  "command": "Create"
}

###
DELETE http://localhost:8080/api/deploy/do/1
Content-Type: application/json
